### ISSUE TITLE
rename to rad-bundle

### ISSUE THREAD

**Issue by tacman** [21TORR/RadBundle#39]
I think 

     "name": "21torr/rad",

should be rad-bundle, that's consistent with most Symfony bundles

**Comment by apfelbox** [comment]
While I know of this convention, I don't love it: it makes the library names longer and introduces clutter: we have quite a lot of packages on packagist and nearly all of them are Symfony bundles.

Also the UI in packagist allows to filter by type (we set the type properly to `symfony-bundle`), so we don't lose discoverability.

But thank you for the suggestion, if we won't apply it at this time.
